use serde::{Deserialize, Serialize};

/// Compact Intermediate Representation for a low-poly Roblox asset.
/// Field names are abbreviated for minimal token cost when generated by an LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Cir {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_part: Option<String>,
    pub parts: Vec<CirPart>,
}

/// A single part in the CIR format.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CirPart {
    /// Part name (unique within model)
    pub n: String,
    /// Position [x, y, z] — center of part
    pub p: [f64; 3],
    /// Size [x, y, z]
    pub s: [f64; 3],
    /// Color [r, g, b] — floats 0.0 to 1.0
    pub c: [f64; 3],
    /// Part type: "block", "wedge", "corner_wedge", "cylinder", "ball"
    #[serde(default = "default_part_type")]
    pub t: String,
    /// Rotation [rx, ry, rz] — Euler degrees
    #[serde(default)]
    pub r: [f64; 3],
    /// Material — Roblox material enum string
    #[serde(default = "default_material")]
    pub m: String,
}

fn default_part_type() -> String {
    "block".into()
}

fn default_material() -> String {
    "SmoothPlastic".into()
}

impl Cir {
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }
}
